# Build Settings
markdown: kramdown
kramdown:
  extensions: ["tables"]
usemathjax: true
highlighter: true

# Permalinks
permalink: pretty

# Setup
title: Eric Keilty
tagline: "Aspiring Amature Mathematician"
description: "Software Engineer/Aspiring Amature Mathematician"
email: epkeilty@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" #http://www.erickeilty.com
shorturl: erickeilty.com
github_username: ekeilty17
paginate: 1

author:
  name: Eric Keilty
  url: https://erickeilty.com
  email: epkeilty@gmail.com

github:
  repo: github.com/ekeilty17/ekeilty17.github.io

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from    # allows URL redirections - https://help.github.com/articles/redirects-on-github-pages
  - jekyll-paginate

# navigation in the side bar
pages_list:
  About: '/about'
  Blog: '/blog'
  R&eacute;sum&eacute;: '/resume'

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - CNAME

# Custom vars
version: 1.0.0
