# Build Settings
markdown: kramdown
kramdown:
  extensions: ["tables"]
usemathjax: true
highlighter: true

# Permalinks
permalink: pretty


# Setup
title: Eric Keilty
tagline: "Aspiring Amature Mathematician"
email: epkeilty@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.erickeilty.com
shorturl: erickeilty.com
github_username: ekeilty17
paginate: 1

author:
  name: Eric Keilty
  url: https://erickeilty.com
  email: epkeilty@gmail.com

github:
  repo: github.com/ekeilty17/ekeilty17.github.io

# Build settings
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  #- jekyll-latex

# the top bar of the webpage
pages_list:
  About: '/about'
  Archive: '/archive'

#exclude:
#  - Gemfile
#  - Gemfile.lock

# Custom vars
version: 1.0.0

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
