#plugins:
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md
  - CNAME

author: Eric Keilty
tagline: Software Engineer

website:
  url: https://erickeilty.com
  baseurl: ""
  host: github.com/ekeilty17/ekeilty17.github.io

social:
  email: epkeilty@gmail.com
  github: https://github.com/ekeilty17
  linkedin: https://www.linkedin.com/in/ekeilty/

markdown: kramdown
kramdown:
  extensions: ["tables"]
usemathjax: true
highlighter: rouge
permalink: pretty

pages_list:
  About: '/about'
  Blog: '/blog'
  R&eacute;sum&eacute;: '/resume'

version: 1.0.0

pdf2svg: 'pdf2svg'    # This is required for the jekyll-tikz custom plugin
                      # it is the 'path to pdf2svg' on your local machine, i.e. how you call the package in the terminal
                      # e.g. `pdf2svg file.pdg file.svg`